// NGMS Prompt Library data: ready-to-paste prompts for Claude, filled in for NGMS.
// Numbers follow the original 50-prompt list (1-6 not included).

export type PackPrompt = { n: number; c: string; t: string; p: string; af: boolean }

export const NGMS_CONTEXT = "NGMS CONTEXT: Next Gen Maintenance Solutions (NGMS), owner Jacques \"NextGen\" Gordon. Property maintenance contractor in the Helderberg Basin (Strand, Gordon's Bay, Somerset West), also takes work in the Overberg, Stellenbosch, Paarl, Worcester and Cape Town (R350 callout outside Helderberg). 11 services: solar panel cleaning (core business), painting, waterproofing, paving, plumbing, electrical, pool fibre lining, high-pressure cleaning, rubble removal, steelwork/welding, handyman. Clients: homeowners, body corporates, security complexes, light commercial. Tagline: One Call. All Solutions. Voice: straight-talking, dependable, systemised, professional but friendly, not corporate. Prices in ZAR, VAT-exclusive, 70% deposit / 30% on completion, EFT or cash only. Solar cleaning: from R550 up to 10 panels, R50/panel from 41 panels, 15% off maintenance plans every 4-6 months. Cape winter rain affects painting, waterproofing and paving scheduling. Channels: Facebook, Instagram, WhatsApp, email.\n\n"

export const AFRIKAANS_LINE = "Give every client-facing piece in English and in Afrikaans."

export const PACK_CATEGORIES = ["All","Client-getting","Marketing","Content","Branding","Offers & Money","Upskilling"] as const

export const PACK_PROMPTS: PackPrompt[] = [
  {"n":7,"c":"Upskilling","t":"14-day plan: sell more from solar cleaning","p":"Create a 14-day learning plan to take me from zero to confident in selling maintenance plans to body corporates and managing agents. Free resources only. Give me a daily action and a milestone. I run a one-man-plus-team contractor business, so keep each day under 45 minutes.","af":false},
  {"n":8,"c":"Upskilling","t":"Explain like I'm 12: waterproofing systems","p":"Explain the difference between torch-on, acrylic liquid membrane and cementitious waterproofing like I am 12 years old. Simple story, real example from a Somerset West flat roof or balcony, zero jargon. Then tell me which one I should quote for which job.","af":false},
  {"n":9,"c":"Upskilling","t":"Top 10 skills for NGMS in 2026","p":"Rank the top 10 skills a multi-trade maintenance contractor in the Western Cape should learn in 2026. Sort by earning potential. Explain why each one matters now. Consider solar/PV cleaning and inspection, waterproofing certification, PIRB and COC requirements, and online marketing.","af":false},
  {"n":10,"c":"Upskilling","t":"30-minute daily routine: quoting speed","p":"Build a 30-minute daily routine to get faster and sharper at quoting and job costing in 30 days. 3 exercises and weekly progress checkpoints. Use my real services and ZAR rates.","af":false},
  {"n":11,"c":"Upskilling","t":"2-week project: build a maintenance package","p":"Design a 2-week project-based learning plan for building and selling a quarterly maintenance package (solar clean + gutters + pressure wash + handyman check). I should have a finished package, price sheet and pitch message at the end.","af":false},
  {"n":12,"c":"Upskilling","t":"Skills audit for NGMS owner","p":"I am the owner, project manager and hands-on contractor of NGMS. Audit my skills. Find my gaps. Tell me exactly what to learn next to earn more this year. Ask me 10 quick questions first, then give the audit.","af":false},
  {"n":13,"c":"Client-getting","t":"3 cold DMs for solar cleaning","p":"Write 3 cold DMs to pitch solar panel cleaning to homeowners and estate residents in Somerset West, Strand and Gordon's Bay on Facebook or Instagram. Personal, not copy-paste. Mention dirt, pollen and dust cutting output, and my free callout inside the Helderberg.","af":true},
  {"n":13,"c":"Client-getting","t":"3 cold DMs for body corporates","p":"Write 3 cold DMs / emails to trustees and managing agents of body corporates and security complexes in the Helderberg. Pitch a combined maintenance offer (pressure washing, painting, waterproofing, paving, gutters, solar). Personal, short, one clear next step.","af":true},
  {"n":14,"c":"Client-getting","t":"10 conversation starters","p":"Give me 10 conversation starters to naturally move an interested follower or enquirer into a paying NGMS client, without being pushy. Split them: 4 for homeowners, 3 for body corporates, 3 for light commercial.","af":true},
  {"n":15,"c":"Client-getting","t":"5 buying signals + exact replies","p":"List 5 signs a follower or enquirer is ready to buy from a maintenance contractor (e.g. asks about price, asks about timing, sends a photo). For each signal, give me the exact WhatsApp reply to send, ending with a booking step.","af":true},
  {"n":16,"c":"Client-getting","t":"Client onboarding process","p":"Design a full client onboarding process for NGMS jobs from enquiry to completion. Cover intake questions per service, site visit, quote, 70% deposit, scheduling around Cape weather, deliverables, completion photos, balance, and follow-up. Make it a checklist I can run for any of the 11 services.","af":false},
  {"n":17,"c":"Client-getting","t":"Proposal template","p":"Write a proposal template for a job worth about R25,000 for a body corporate (e.g. exterior repaint plus waterproofing on common areas). Include scope, timeline (with winter rain buffer), investment in ZAR excl. VAT, 70/30 terms, guarantee, and next steps.","af":true},
  {"n":18,"c":"Client-getting","t":"5 creative ways to land high-paying clients","p":"Give me 5 creative ways to land high-paying maintenance clients in the Helderberg. No platforms, no job boards, no cold DMs. Think managing agents, estate agents, letting agents, property managers, insurance-related repairs and referral partnerships.","af":false},
  {"n":19,"c":"Marketing","t":"10 hooks: solar cleaning","p":"Write 10 marketing hooks for solar panel cleaning aimed at Helderberg homeowners on Facebook. Mix story, data and FOMO angles. Keep them punchy and local.","af":true},
  {"n":19,"c":"Marketing","t":"10 hooks: winter waterproofing","p":"Write 10 marketing hooks for waterproofing and damp treatment aimed at Cape homeowners heading into winter rain. Mix story, data and FOMO angles.","af":true},
  {"n":20,"c":"Marketing","t":"7-day Facebook launch plan","p":"Create a 7-day Facebook-only launch plan for a new NGMS maintenance package. Daily goal, copy, and engagement target. Use before/after photos, a client testimonial, a limited-time offer and a WhatsApp booking CTA.","af":true},
  {"n":21,"c":"Marketing","t":"10 reasons people don't book + replies","p":"List 10 reasons people don't book a maintenance contractor (price, trust, timing, previous bad experience, DIY). Write a short persuasive reply for each that removes the doubt. Keep the tone straight-talking and friendly.","af":true},
  {"n":22,"c":"Marketing","t":"5-email welcome sequence","p":"Write a 5-email welcome sequence for new enquiries and subscribers on NGMS maintenance tips. Each email builds trust (tips, before/afters, guarantee, testimonial) and ends with a soft offer. Include subject lines.","af":true},
  {"n":23,"c":"Marketing","t":"5 CTA variations","p":"Give me 5 CTA variations for selling solar panel cleaning in a Facebook post caption. Natural, not desperate or salesy. Each one should push to WhatsApp.","af":true},
  {"n":24,"c":"Marketing","t":"Referral system","p":"Build a referral system that turns NGMS clients into active promoters. Include incentives I can afford (e.g. discount on next service, free gutter check), and the exact WhatsApp message to send after a job is done.","af":true},
  {"n":25,"c":"Branding","t":"5 positioning statements","p":"Write 5 brand positioning statements: \"I help [homeowners, body corporates and complexes in the Helderberg] achieve [well-maintained property] without [chasing 5 different contractors].\" 5 unique variations, all built around One Call. All Solutions.","af":false},
  {"n":26,"c":"Branding","t":"Brand voice guide","p":"Create a brand voice guide for NGMS. I want to sound straight-talking, dependable, systemised and friendly. Give do's, don'ts, and 5 example phrases. Show how the voice changes for a body corporate email vs a Facebook post vs a WhatsApp quote follow-up.","af":false},
  {"n":27,"c":"Branding","t":"Facebook bio rewrite","p":"Rewrite my Facebook page bio to sound more confident and clear. Under 150 characters. Give me 5 options. Mention solar cleaning, multi-trade, and Helderberg. Current bio: [PASTE BIO HERE].","af":false},
  {"n":28,"c":"Branding","t":"8 content pillars","p":"Generate 8 content pillars for the NGMS brand. Under each pillar, give 3 post ideas with ready-to-use hooks. Cover before/afters, solar tips, winter prep, job-in-progress, team, client wins, education, and offers.","af":true},
  {"n":29,"c":"Branding","t":"One-page brand brief","p":"Write a one-page brand brief for NGMS. Mission, audience, tone, visual style (Jet Black, Power Purple, Solar Orange, Eco Green; Space Grotesk and Inter), and key message.","af":false},
  {"n":30,"c":"Branding","t":"5 positioning angles vs other handymen","p":"Give me 5 positioning angles that make NGMS stand out from every other generic handyman in the Helderberg. Lean on: one project manager and one call, registered electrician and PIRB plumber signing off COCs, systemised quotes, before/after proof.","af":false},
  {"n":31,"c":"Offers & Money","t":"10 ways to earn more this month","p":"List 10 realistic ways NGMS can make more money this month without hiring. Consider winter/spring seasonality, upsells to existing clients, body corporate contracts, and quiet-day filler jobs.","af":false},
  {"n":32,"c":"Offers & Money","t":"Package tiers: Basic / Standard / Premium","p":"Turn my services into 3 maintenance packages: a basic, a standard and a premium tier for homeowners. Give ZAR prices excl. VAT at Helderberg market rates, what each includes, and who it is for. Use solar cleaning as the anchor.","af":false},
  {"n":33,"c":"Offers & Money","t":"Full offer stack: solar cleaning","p":"Build a full offer stack for solar panel cleaning selling to homeowners and complexes. Include pricing tiers (from R550 up to 10 panels, R50/panel from 41), deliverables, maintenance plan with 15% off, and upsells (gutters, pressure wash, roof soft wash).","af":true},
  {"n":34,"c":"Offers & Money","t":"Free-to-paid Facebook funnel","p":"Design a free-to-paid funnel using Facebook content to convert followers into paying NGMS clients. Start from free tips, then a lead magnet, then WhatsApp conversation, then quote, then maintenance plan.","af":true},
  {"n":35,"c":"Offers & Money","t":"Sales page outline: maintenance plans","p":"Write a full sales page outline for NGMS quarterly maintenance plans that solve the problem of property upkeep for busy homeowners and body corporates. Headline, benefits, guarantee, FAQs and CTA.","af":true},
  {"n":36,"c":"Offers & Money","t":"5 recurring income models","p":"Suggest 5 recurring income models for a property maintenance contractor in the Western Cape. Pricing strategy and retention tactics included. Think quarterly solar cleans, annual gutter and roof checks, body corporate retainers and seasonal packages.","af":false},
  {"n":37,"c":"Offers & Money","t":"10 lead magnets I can build in 7 days","p":"Generate 10 lead magnets NGMS could build and start using within 7 days (e.g. winter home prep checklist, solar cleaning output calculator, damp signs guide). For each, say who it is for and which service it leads to.","af":true},
  {"n":38,"c":"Offers & Money","t":"Free guide: winter home prep","p":"Outline a short guide 'Winter-Proof Your Home in the Helderberg' that a homeowner can read in 10 minutes. Sections, tips, and a soft CTA to book a roof, gutter, damp or waterproofing check.","af":true},
  {"n":39,"c":"Offers & Money","t":"Lead magnet that leads to solar plan","p":"Design a lead magnet that solves one specific problem for homeowners (dirty panels losing output) and naturally leads them to book a solar cleaning maintenance plan.","af":true},
  {"n":40,"c":"Offers & Money","t":"Productise a service","p":"Turn [SERVICE, e.g. exterior high-pressure cleaning] into a productised service with fixed pricing, clear deliverables, and a repeatable process. Include size bands, prices in ZAR excl. VAT, what is included and excluded, and a standard timeline.","af":false},
  {"n":41,"c":"Offers & Money","t":"Landing page copy: solar cleaning","p":"Write landing page copy for a solar panel cleaning offer in the Helderberg. Headline, bullets, guarantee, price tiers, and CTA to WhatsApp.","af":true},
  {"n":42,"c":"Offers & Money","t":"Service ladder: free to premium","p":"Map a complete service ladder for NGMS. Start from free content, then low-cost entry (solar clean), then repeat service (maintenance plan), then bigger projects (paint, waterproofing, paving), then premium body corporate retainer. Show how each step connects.","af":false},
  {"n":43,"c":"Content","t":"30-day content calendar","p":"Build a 30-day Facebook and Instagram content calendar for NGMS. Daily hooks, formats, and best posting times for Facebook. Rotate across all 11 services, with solar cleaning as the anchor and winter prep themes.","af":true},
  {"n":44,"c":"Content","t":"15 short video ideas","p":"Generate 15 short video ideas about property maintenance for homeowners. Opening hook plus visual direction for each. Everything must be filmable on a phone on a job site.","af":false},
  {"n":45,"c":"Content","t":"Long idea into 5 scripts","p":"Break this long-form idea into 5 scripts under 60 seconds each. Punchy hook for every one: [PASTE IDEA, e.g. why dirty solar panels lose output]","af":false},
  {"n":46,"c":"Content","t":"10 scroll-stopping opening lines","p":"Write 10 scroll-stopping opening lines about [TOPIC, e.g. damp walls in winter] using curiosity gaps and pattern interrupts.","af":true},
  {"n":47,"c":"Content","t":"Tighten a caption","p":"Rewrite this caption to be shorter, punchier and more engaging. Keep the core message: [PASTE CAPTION]","af":false},
  {"n":48,"c":"Content","t":"Weekly batching system","p":"Create a weekly batching system for a busy contractor producing videos, carousels and text posts consistently. Use job-site photos and clips I already take. Keep it under 2 hours a week.","af":false},
  {"n":49,"c":"Content","t":"Audit a content idea","p":"Audit this content idea for me. Rate hook, relevance, shareability and viral potential 1-10 for a Helderberg audience: [PASTE IDEA]","af":false},
  {"n":50,"c":"Content","t":"10 'What most people get wrong'","p":"Create 10 'What Most People Get Wrong About [TOPIC]' ideas for NGMS. Contrarian and debate-worthy. Cover solar cleaning, painting in winter, waterproofing, paving, and pressure washing.","af":true},
]
