CREATE TABLE quote_requests (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  full_name TEXT,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  notes TEXT,
  panel_count INTEGER,
  system_kw DECIMAL,
  soiling_loss_pct DECIMAL,
  annual_financial_loss DECIMAL,
  estimated_cleaning_cost DECIMAL,
  net_annual_savings DECIMAL,
  payback_months DECIMAL,
  submitted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ DEFAULT NOW()
);
